relayjs/eslint-plugin-relay

eslint-plugin-relay.js
package.json
test/test.js
yarn.lock

Closes #2 
This adds a new lint rule that checks for usage of generated flow types, and automatically adds them if it doesn't. I've added 11 test cases as well.
As a side note, I had to bring in `babel-eslint` (to parse flow) and upgrade to eslint version ^4.1.0 for this feature: https://github.com/eslint/eslint/pull/8101.
> I chose `babel-eslint` over `esprima-fb` because the latter broke some old test cases as `esprima` uses different naming conventions than the default `espree` parser)

Automatically import flow types

---

eslint-plugin-relay.js
test/test.js

Closes #5
Also, We didn't support the case where you could've done something like:
```
type Props = {
field: ?Container_field,
}
```
(if you set the imported type to be nullable)
This PR fixes that case too :)

Support type aliases

---

eslint-plugin-relay.js

**what is the change?:**
Changed two cases of destructuring assignment to use older style JS.
**why make this change?:**
In Draft.js we support development with node.js 4.x, which does not
support ES6 destructuring.[1]
We also use this plug-in, since it is a peer dependency of
eslint-config-fbjs.[2]
[1]: https://github.com/nodejs/node/issues/3101
[2]: https://github.com/facebook/fbjs/blob/master/packages/eslint-config-fbjs/package.json#L29
**test plan:**
I locally made these changes, ran `yarn lint` when running node v4.8.4,
and it didn't throw errors.
Otherwise it was throwing this error -
```
Unexpected token {
Referenced from: /home/travis/build/facebook/draft-js/.eslintrc.js
SyntaxError: Unexpected token {
Referenced from: /home/travis/build/facebook/draft-js/.eslintrc.js
at …
```

Remove destructuring assignment to support node.js 4.x

---

README.md

Clicking on the badge currently goes to the Travis page for 'facebook/relay'.
This fixes that

Update badge link to point to the correct repo

---

src/rule-unused-fields.js
test/unused-fields.js

Syntax errors are handled by `rule-graphql-syntax`, everything else
should just ignore invalid syntax.
Fixes #39

Ignore syntax error in unused-field rule

---

package.json
yarn.lock

Upgrades to using v14 of `graphql`, so that when we bump Relay's version number, it only needs to install a single version of `graphql` rather than both `0.13` and `14.0`

Bump graphql-js version to 14.0.0

---

src/rule-no-future-added-value.js
test/future-added-value.js
test/test.js

Allow using `%future added value` within a cast in the default case of a switch statement. Use this to get an exhaustive switch case in flow while also requiring an explicit default value:
```js
// type SomeRelayEnum = 'FOO' | 'BAR' | '%future added value';
function test(foo: SomeRelayEnum): string {
switch(foo) {
case 'FOO':
return 'foo';
case 'BAR':
return 'bar';
default:
(foo: '%future added value');
return 'default';
}
}
```
[Try Flow](https://flow.org/try/#0C4TwDgpgBAyg9gWwgJQgGwIYgKIDsCuCUAvFAOQBiA8lWVAD7kBCAgsnY2QKQBm+w+AE7QMAE1ERRUAG4Y0+CGQDcAKBV9cAY2ABLOLijAIAZ2AAKHnDgAuWIhToseQgEpbpwTtwBzKAG8VKChjAHcdYE0ACwsrF39AoKhNDGNoShoyawTEqGEBQQMySzhlbKSUtNZ2LJygvKFCgCMMQVKciR4MfDRgGtqYm3JefiERcUkZOQUyF1Va3Ih8wo6unraoAF8VDaA)
Added test cases, ran `yarn test`, ran `yarn run prettier`

Allow future added value within default case cast

---

src/rule-unused-fields.js
test/unused-fields.js

Sometimes, it's useful to just know the existence of an object, but the GraphQL spec enforces that some field is queried. This ignores `__typename` to have a generally cheap field that doesn't trigger the linter.

Ignore __typename in unused field rule

---

src/rule-generated-flow-types.js
test/test.js

This format of defining props flow types as a class property was
replaced a long time ago now. Removing and updating the tests to the new
format.

Removes support for legacy React.Component definitions

---

src/rule-generated-flow-types.js
test/test.js

This makes the lint for useFragment flow typing more strict by requiring
the import of the `xyz$key` type instead of anything from the generated
module.

Require MyFragment$key type for useFragment

---

src/rule-generated-flow-types.js
test/test.js

Fixes a fatal where `validateObjectTypeAnnotation()` fatals when passed an unexpected value (when  `propType` isn't an `ObjectTypeAnnotation` as expected). This can occur when GenericTypeAnnotations aren't filtered later in the file. The simple fix was to just filter out non-ObjectTypeAnnotation values, but I noticed this bug because of an example involving `$ReadOnly<Props>`. I realized we aren't unwrapping ReadOnly values, and also aren't fully resolving aliases, so I implemented support for those and then filtered out non-object types only afterwards.

Fix generated flow type rule w readonly/aliased types

---

src/rule-graphql-naming.js
src/utils.js
test/test.js

This is used for internal migration to split legacy RelayCompat code
from RelayModern.

Allow graphql_DEPRECATED tag

---

.travis.yml

According to https://nodejs.org/en/about/releases/ node 8, 10, and 12 are the current supported versions.

Update node version to current supported

---

src/rule-generated-flow-types.js
test/test.js

usePaginationFragment and useRefetchableFragment need to specify a type parameter for the query type.
Test plan:
- New unit tests

Lint for misuse of usePaginationFragment and useRefetchableFragment without providing query type param

---

src/rule-generated-flow-types.js
test/test.js

This commit ensures that we also verify that the correct ref types are imported when using `useRefetchableFragment` and `usePaginationFragment`. Currently we only do so for `useFragment`.
Test Plan:
- New and updated unit tests

Also verify correct ref type is used for useRefetchable and usePagination fragments

---

test/test.js

The tests for autofix output are disabled by `HAS_ESLINT_BEEN_UPGRADED_YET`, enabling it for some of the tests where the expected output matches. There are still several `HAS_ESLINT_BEEN_UPGRADED_YET` left where the results don't match.

[1/n]Enable some snapshot tests for the autofix output

---

src/rule-generated-flow-types.js
test/test.js

Currently our validation for flow type doesn't process object spread, this caused the following case to report an error but it is actually a valid case.
```
type RelayProps = {|
+user: MyComponent_user,
|}
type Props = {|
...RelayProps,
id: 3
|}
class MyComponent extends React.Component<Props> {
render() {
return <div />;
}
}
```
This PR fix the issue by also checking the referenced type recursively.

Follow flow type objectSpread to get the actual propType

---

eslint-plugin-relay.js
src/rule-hook-required-argument.js
test/hook-required-argument.js

Currently flow doesn't check if the second argument is passed to hooks when the type is optional, so `useFragment(query)` will pass flow check but it should not be allowed.
This diff adds the check on the second argument.

Ensure the second argument is passed to relay hooks

---

src/rule-generated-flow-types.js
test/test.js

This change will help provide better type safety for mutations.

Added lint rule to the `commitMutation` function to enforce type annotation

---

package.json
src/rule-generated-flow-types.js

The was an error: 
```
TypeError: Cannot read property 'name' of undefined
```

Fix runtime error in the plugin. Bump version to 1.4.1

---

src/rule-must-colocate-fragment-spreads.js
test/must-colocate-fragment-spreads.js

Using dynamic import like import() would cause a crash.
closes #99

Fix crash when using dynamic import with must-colocate-fragment-spreads

---

package.json
src/utils.js
test/future-added-value.js
test/hook-required-argument.js
test/must-colocate-fragment-spreads.js
test/test.js
test/unused-fields.js
yarn.lock

ESLint 7 (or 6) removed the start field on node, it actually triggers this error:
`Error: Use node.range[0] instead of node.start`
Also I assume they changed whether the start is inclusive or not since everything is offset by 1 now, hence the random + 1.
The `parser` option of `RuleTester` now requires absolute paths so I added `require.resolve`.
Fix error in compat check in `getLocFromIndex`. It checks for `getSourceCode` but it should be `getLocFromIndex`.
Tested by running tests on eslint 5 and 7.
Also wanted to test eslint 3.5 as it is mentionned in a comment but tests failed for other unrelated reasons. Not sure if supporting 3.5 is still relevent now.

Support eslint 7

---

README.md
eslint-plugin-relay.js
src/rule-function-required-argument.js
test/function-required-argument.js

Following https://github.com/relayjs/eslint-plugin-relay/issues/106 issue.
This change adds new rule to check missing argument for `readInlineData` function call. Docs https://relay.dev/docs/en/graphql-in-relay#inline
Also updates `.eslintrc.js` example in readme.

add "function-required-argument" rule

---

README.md
src/rule-must-colocate-fragment-spreads.js
src/rule-unused-fields.js
src/utils.js
test/must-colocate-fragment-spreads.js
test/unused-fields.js

This PR adds the ability to suppress eslint reporting within graphql tags:
```js
graphql`
fragment foo on Page {
...unused1
}
`
```
Note that only the `eslint-disable-next-line` form of suppression works. `eslint-disable-line` doesn't currently work until graphql-js provides support for [parsing Comment nodes](https://github.com/graphql/graphql-js/issues/2241) in their AST.

Add eslint disable support

---

package.json
src/rule-generated-flow-types.js
test/test.js

This PR adds a lint rule and autofix for `useMutation` without a flow type parameter.

Require flow type in useMutation

---

src/rule-graphql-naming.js
src/utils.js
test/test.js

The `graphql_DEPRECATED` tag was used for RelayCompat which was long
deleted in OSS as well as internally. Cleans up a bit of code from the
linter.

Remove RelayCompat support

---

src/rule-must-colocate-fragment-spreads.js

`rule-must-colocate-fragment-spreads.js` references the intro page which is broken. This fixes the link to the correct URL.

Fix the intro page link

---

eslint-plugin-relay.js
package.json
src/rule-generated-typescript-types.js
test/generated-typescript-types.js
yarn.lock

Based heavily on #115, thanks @llldar to do the ground work.
Note that #119 is a different way of fixing the same underlying issue. 
I wanted to open this PR either way, because it's a different way of getting to a solution (Please feel free to choose whatever is considered the better one!).
Notable differences between the two PR's: because this is a different file then the flow rule, this has (and can) leverage the AST returned from the @typescript-eslint/parser package. 
This let's us actually disable a workaround needed in flow (yay).
The test suit is mostly copied from `generated-flow-types`. Some test where changed / removed, because they don't really make sense in the TS world (imo anyhow).
There might be some shared code between the to `generated-XYZ-types` rules that could be …

Add "generated-typescript-types" rule, and "ts-recommended"

---

.github/workflows/ci.yml
CONTRIBUTING.md

Ported from https://github.com/facebook/relay/blob/main/.github/workflows/ci.yml
* For each `main` push, this will publish a prerelease package that follows the format `0.0.0-main-SHA`
* For tag pushes it will publish a package that follows the name of the tag.
TODO:

[ci] Add release automation scripts

---

.github/workflows/ci.yml

This should help us debug what's going on, but also will allow us to retry with the newly created "Classic"/"Automation" token that I've setup.
For some reason rerunning the previously failed CI run is not available any more. I suspect rerunning expires at some point in time?

Increase verbosity of npm publish from CI

---

.github/workflows/ci.yml

I suspect this might be required to allow our authentication to work.
From the [setup-node docs](https://github.com/actions/setup-node/#usage):
```
registry-url: ''
```
Note this also mirrors what we do in the [Relay repo](https://github.com/facebook/relay/blob/05689b07f3415a028c6cbed8f3435d78690ebeb1/.github/workflows/ci.yml#L227C11-L227C52) where this flow seems to be working.

Add registry-url to setup-node in CI

---

.github/workflows/ci.yml
.prettierrc
package.json
src/rule-generated-typescript-types.js
yarn.lock

`typeParameters` has been deprecated and replaced by `typeArguments` in v6, and finally removed in v8. This makes v6 the minimum version, so it's a breaking change.

Make compatible with typescript-eslint 8

---

.github/workflows/ci.yml
README.md
package.json
src/rule-generated-typescript-types.js
src/utils.js
test/compat-uses-vars.js
test/function-required-argument.js
test/future-added-value.js
test/generated-typescript-types.js
test/hook-required-argument.js
test/must-colocate-fragment-spreads.js
test/test.js
test/unused-fields.js

This PR addresses some CI/CD pipeline issues:
- Upgrades `actions/checkout` to v4
- Upgrades `actions/setup-node` to v4
- Pins Yarn to v1 to prevent automatic upgrades to Yarn 2
- Resolves Prettier formatting issues that were causing pipeline failures

chore: update ci workflow actions
